apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: imcx6jmsq-python 
  janus-idp.io/tekton: imcx6jmsq-python
  backstage.io/kubernetes-id: imcx6jmsq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: imcx6jmsq-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml