apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: imcx6jmsq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: imcx6jmsq-python 
  name: imcx6jmsq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: imcx6jmsq-python 
